{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "bfcbc041",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pymysql in /Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages (1.0.2)\r\n"
     ]
    }
   ],
   "source": [
    "#imports\n",
    "!pip install pymysql\n",
    "import pymysql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bf13847f",
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationalError",
     "evalue": "(2003, \"Can't connect to MySQL server on 'dev-lightning-db.cygxsxxfo1d6.us-east-1.rds.amazonaws.com' (timed out)\")",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mtimeout\u001b[0m                                   Traceback (most recent call last)",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/pymysql/connections.py:613\u001b[0m, in \u001b[0;36mConnection.connect\u001b[0;34m(self, sock)\u001b[0m\n\u001b[1;32m    612\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 613\u001b[0m     sock \u001b[38;5;241m=\u001b[39m \u001b[43msocket\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcreate_connection\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    614\u001b[0m \u001b[43m        \u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mhost\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mport\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect_timeout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\n\u001b[1;32m    615\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    616\u001b[0m     \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/socket.py:844\u001b[0m, in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address)\u001b[0m\n\u001b[1;32m    843\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 844\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m err\n\u001b[1;32m    845\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    846\u001b[0m     \u001b[38;5;66;03m# Break explicitly a reference cycle\u001b[39;00m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/socket.py:832\u001b[0m, in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address)\u001b[0m\n\u001b[1;32m    831\u001b[0m     sock\u001b[38;5;241m.\u001b[39mbind(source_address)\n\u001b[0;32m--> 832\u001b[0m \u001b[43msock\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43msa\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    833\u001b[0m \u001b[38;5;66;03m# Break explicitly a reference cycle\u001b[39;00m\n",
      "\u001b[0;31mtimeout\u001b[0m: timed out",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "Input \u001b[0;32mIn [7]\u001b[0m, in \u001b[0;36m<cell line: 6>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      3\u001b[0m password \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mntslightningtest\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m      4\u001b[0m database \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m----> 6\u001b[0m connection \u001b[38;5;241m=\u001b[39m \u001b[43mpymysql\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhost\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mhost\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43muser\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43muser\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpassword\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpassword\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mport\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m3306\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdatabase\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdatabase\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m connection:\n\u001b[1;32m      8\u001b[0m     cur \u001b[38;5;241m=\u001b[39m connection\u001b[38;5;241m.\u001b[39mcursor()\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/pymysql/connections.py:353\u001b[0m, in \u001b[0;36mConnection.__init__\u001b[0;34m(self, user, password, host, database, unix_socket, port, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)\u001b[0m\n\u001b[1;32m    351\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_sock \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    352\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m--> 353\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/pymysql/connections.py:664\u001b[0m, in \u001b[0;36mConnection.connect\u001b[0;34m(self, sock)\u001b[0m\n\u001b[1;32m    662\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m DEBUG:\n\u001b[1;32m    663\u001b[0m         \u001b[38;5;28mprint\u001b[39m(exc\u001b[38;5;241m.\u001b[39mtraceback)\n\u001b[0;32m--> 664\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exc\n\u001b[1;32m    666\u001b[0m \u001b[38;5;66;03m# If e is neither DatabaseError or IOError, It's a bug.\u001b[39;00m\n\u001b[1;32m    667\u001b[0m \u001b[38;5;66;03m# But raising AssertionError hides original error.\u001b[39;00m\n\u001b[1;32m    668\u001b[0m \u001b[38;5;66;03m# So just reraise it.\u001b[39;00m\n\u001b[1;32m    669\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m\n",
      "\u001b[0;31mOperationalError\u001b[0m: (2003, \"Can't connect to MySQL server on 'dev-lightning-db.cygxsxxfo1d6.us-east-1.rds.amazonaws.com' (timed out)\")"
     ]
    }
   ],
   "source": [
    "host = 'dev-lightning-db.cygxsxxfo1d6.us-east-1.rds.amazonaws.com'\n",
    "user = 'admin'\n",
    "password = 'ntslightningtest'\n",
    "database = ''\n",
    "\n",
    "connection = pymysql.connect(host=host, user=user, password=password, port=3306, database=database)\n",
    "with connection:\n",
    "    cur = connection.cursor()\n",
    "    cur.execute(\"SELECT VERSION()\")\n",
    "    version = cur.fetchone()\n",
    "    print(\"Database version: {} \".format(version[0]))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dfb343f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import libraries\n",
    "from sshtunnel import SSHTunnelForwarder\n",
    "\n",
    "# SSH (ec2_public_dns, ec2_user, pem_path, remote_bind_address=(rds_instance_access_point, port))\n",
    "with SSHTunnelForwarder(('ec2-52-202-194-76.public-ec2-instance.amazonaws.com'), ssh_username=\"ec2-user\", ssh_pkey=\"~/ssh-tunnel-rds.pem\", remote_bind_address=('private-rds-instance.ckfkidfytpr4.us-east-1.rds.amazonaws.com', 3306)) as tunnel:\n",
    "    print(\"****SSH Tunnel Established****\")\n",
    "\n",
    "    db = pymysql.connect(\n",
    "          host='127.0.0.1', user=\"rdsuser\",password=\"rdspassword\",\n",
    "          port=tunnel.local_bind_port, database=\"dbName\")\n",
    "    # Run sample query in the database to validate connection\n",
    "    try:\n",
    "        # Print all the databases\n",
    "        with db.cursor() as cur:\n",
    "         # Print all the tables from the database\n",
    "            cur.execute('SHOW TABLES FROM dbName')\n",
    "            for r in cur:\n",
    "                print(r)\n",
    "\n",
    "            # Print all the data from the table\n",
    "            cur.execute('SELECT * FROM table_name')\n",
    "            for r in cur:\n",
    "                print(r)\n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "print(\"YAYY!!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "8ca17da5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting mysql\n",
      "  Downloading mysql-0.0.3-py3-none-any.whl (1.2 kB)\n",
      "Collecting mysqlclient\n",
      "  Downloading mysqlclient-2.1.1.tar.gz (88 kB)\n",
      "\u001b[K     |████████████████████████████████| 88 kB 7.3 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_98a461d1e5bb43b7858f3e56efe22b1f/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_98a461d1e5bb43b7858f3e56efe22b1f/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-zej5rdoa\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_98a461d1e5bb43b7858f3e56efe22b1f/\n",
      "    Complete output (15 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_98a461d1e5bb43b7858f3e56efe22b1f/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_98a461d1e5bb43b7858f3e56efe22b1f/setup_posix.py\", line 70, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_98a461d1e5bb43b7858f3e56efe22b1f/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    mysql_config --version\n",
      "    mariadb_config --version\n",
      "    mysql_config --libs\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/50/5f/eac919b88b9df39bbe4a855f136d58f80d191cfea34a3dcf96bf5d8ace0a/mysqlclient-2.1.1.tar.gz#sha256=828757e419fb11dd6c5ed2576ec92c3efaa93a0f7c39e263586d1ee779c3d782 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.1.0.tar.gz (87 kB)\n",
      "\u001b[K     |████████████████████████████████| 87 kB 17.0 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_46cad6a31d8240bcb44b6f723fbd1fdb/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_46cad6a31d8240bcb44b6f723fbd1fdb/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-pllqxwpc\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_46cad6a31d8240bcb44b6f723fbd1fdb/\n",
      "    Complete output (15 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_46cad6a31d8240bcb44b6f723fbd1fdb/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_46cad6a31d8240bcb44b6f723fbd1fdb/setup_posix.py\", line 70, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_46cad6a31d8240bcb44b6f723fbd1fdb/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    mysql_config --version\n",
      "    mariadb_config --version\n",
      "    mysql_config --libs\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz#sha256=973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.0.3.tar.gz (88 kB)\n",
      "\u001b[K     |████████████████████████████████| 88 kB 29.9 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8dff23977e1a4e758c19b80502ae17e3/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8dff23977e1a4e758c19b80502ae17e3/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-mc6qnkms\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8dff23977e1a4e758c19b80502ae17e3/\n",
      "    Complete output (15 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8dff23977e1a4e758c19b80502ae17e3/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8dff23977e1a4e758c19b80502ae17e3/setup_posix.py\", line 70, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8dff23977e1a4e758c19b80502ae17e3/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    mysql_config --version\n",
      "    mariadb_config --version\n",
      "    mysql_config --libs\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz#sha256=f6ebea7c008f155baeefe16c56cd3ee6239f7a5a9ae42396c2f1860f08a7c432 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.0.2.tar.gz (88 kB)\n",
      "\u001b[K     |████████████████████████████████| 88 kB 9.5 MB/s  eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_cd5254db8e0a4e0b98c09ce79f13f924/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_cd5254db8e0a4e0b98c09ce79f13f924/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-k3k0tqs1\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_cd5254db8e0a4e0b98c09ce79f13f924/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_cd5254db8e0a4e0b98c09ce79f13f924/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_cd5254db8e0a4e0b98c09ce79f13f924/setup_posix.py\", line 65, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_cd5254db8e0a4e0b98c09ce79f13f924/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0e/68/f79de0e0fcdb041783124b825771e0ba6a3d0893b7b4c4735f130e42af47/mysqlclient-2.0.2.tar.gz#sha256=8df057b08fc27d8f7106bfa997d0a21e2acef017f905f06d6fb0aa6a20d4d2b2 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25h  Downloading mysqlclient-2.0.1.tar.gz (87 kB)\n",
      "\u001b[K     |████████████████████████████████| 87 kB 23.7 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_eaed9854d4544884aeed1779ef8c7b9a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_eaed9854d4544884aeed1779ef8c7b9a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-lrwyt42k\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_eaed9854d4544884aeed1779ef8c7b9a/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_eaed9854d4544884aeed1779ef8c7b9a/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_eaed9854d4544884aeed1779ef8c7b9a/setup_posix.py\", line 65, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_eaed9854d4544884aeed1779ef8c7b9a/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a5/e1/e5f2b231c05dc51d9d87fa5066f90d1405345c54b14b0b11a1c859020f21/mysqlclient-2.0.1.tar.gz#sha256=fb2f75aea14722390d2d8ddf384ad99da708c707a96656210a7be8af20a2c5e5 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.0.0.tar.gz (87 kB)\n",
      "\u001b[K     |████████████████████████████████| 87 kB 27.0 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7c03045aa5cb4044a390da67fe77302b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7c03045aa5cb4044a390da67fe77302b/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-d1jxqxxw\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7c03045aa5cb4044a390da67fe77302b/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7c03045aa5cb4044a390da67fe77302b/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7c03045aa5cb4044a390da67fe77302b/setup_posix.py\", line 65, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7c03045aa5cb4044a390da67fe77302b/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ca/cf/dd8124bf8b3d2ae465db9c8ce35c51650c31784b095f41faf6f8cad987a0/mysqlclient-2.0.0.tar.gz#sha256=201dfcc2a3c8a0859ea399947f1af8abe74b706beba0ebac149180d9d7b0f6e8 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.6.tar.gz (85 kB)\n",
      "\u001b[K     |████████████████████████████████| 85 kB 20.1 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5281cfd91e854ef390f4f5156a9dd4cd/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5281cfd91e854ef390f4f5156a9dd4cd/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-97p3v5_d\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5281cfd91e854ef390f4f5156a9dd4cd/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5281cfd91e854ef390f4f5156a9dd4cd/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5281cfd91e854ef390f4f5156a9dd4cd/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5281cfd91e854ef390f4f5156a9dd4cd/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz#sha256=f3fdaa9a38752a3b214a6fe79d7cae3653731a53e577821f9187e67cbecb2e16 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.5.tar.gz (86 kB)\n",
      "\u001b[K     |████████████████████████████████| 86 kB 8.1 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_14b61275af5e4b9aa44bb3219a18ee44/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_14b61275af5e4b9aa44bb3219a18ee44/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-yrkuq64x\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_14b61275af5e4b9aa44bb3219a18ee44/\n",
      "    Complete output (12 lines):\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_14b61275af5e4b9aa44bb3219a18ee44/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_14b61275af5e4b9aa44bb3219a18ee44/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_14b61275af5e4b9aa44bb3219a18ee44/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f8/9b/5db9a03e2088a87c26e3e4d4c7f7e8f4c2dbae610f9521cdfac15755a795/mysqlclient-1.4.5.tar.gz#sha256=e80109b0ae8d952b900b31b623181532e5e89376d707dcbeb63f99e69cefe559 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.4.tar.gz (86 kB)\n",
      "\u001b[K     |████████████████████████████████| 86 kB 20.8 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_b13cc4c07ea24beba0350265627c630b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_b13cc4c07ea24beba0350265627c630b/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-o2haub50\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_b13cc4c07ea24beba0350265627c630b/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_b13cc4c07ea24beba0350265627c630b/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_b13cc4c07ea24beba0350265627c630b/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_b13cc4c07ea24beba0350265627c630b/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz#sha256=9c737cc55a5dc8dd3583a942d5a9b21be58d16f00f5fefca4e575e7d9682e98c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.3.tar.gz (86 kB)\n",
      "\u001b[K     |████████████████████████████████| 86 kB 23.8 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_d87033e841dc4374b61a70a485b83b70/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_d87033e841dc4374b61a70a485b83b70/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-w8cbm3ud\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_d87033e841dc4374b61a70a485b83b70/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_d87033e841dc4374b61a70a485b83b70/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_d87033e841dc4374b61a70a485b83b70/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_d87033e841dc4374b61a70a485b83b70/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/13/37/6c941aabeb78464a538b7d43266bfae645993779e3ca3e12fe82b4590f52/mysqlclient-1.4.3.tar.gz#sha256=0d3eeb97534c9f42e9b65bd35c1a35fadc2f6d7ea5d9fdbda5339a569156344b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.2.post1.tar.gz (85 kB)\n",
      "\u001b[K     |████████████████████████████████| 85 kB 16.8 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_261a49c5715f48eca7f1d51710e35a66/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_261a49c5715f48eca7f1d51710e35a66/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-o4vhbd6s\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_261a49c5715f48eca7f1d51710e35a66/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_261a49c5715f48eca7f1d51710e35a66/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_261a49c5715f48eca7f1d51710e35a66/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_261a49c5715f48eca7f1d51710e35a66/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz#sha256=f257d250f2675d0ef99bd318906f3cfc05cef4a2f385ea695ff32a3f04b9f9a7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.2.tar.gz (85 kB)\n",
      "\u001b[K     |████████████████████████████████| 85 kB 16.2 MB/s eta 0:00:01\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7796863aeeef4a53813dae0f28bc3257/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7796863aeeef4a53813dae0f28bc3257/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-tcdchtfl\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7796863aeeef4a53813dae0f28bc3257/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7796863aeeef4a53813dae0f28bc3257/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7796863aeeef4a53813dae0f28bc3257/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_7796863aeeef4a53813dae0f28bc3257/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/73/79/67ddf24ac31b05d741f0ac87fa612c7a11bab1b39b8270ed7344d149f8af/mysqlclient-1.4.2.tar.gz#sha256=b95edaa41d6cc47deecabcdcbb5ab437ad9ae6d8955f5cf10d1847b37e66ef5e (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.1.tar.gz (85 kB)\n",
      "\u001b[K     |████████████████████████████████| 85 kB 14.1 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_a2514932ea6e4d0a914dbf273f58d081/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_a2514932ea6e4d0a914dbf273f58d081/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-a07fxg_u\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_a2514932ea6e4d0a914dbf273f58d081/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_a2514932ea6e4d0a914dbf273f58d081/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_a2514932ea6e4d0a914dbf273f58d081/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_a2514932ea6e4d0a914dbf273f58d081/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/de/d7/919042fb7ed78a89e21c4e43d5daed90d5df18ec183bae3de493a7d9e3ed/mysqlclient-1.4.1.tar.gz#sha256=a62220410e26ce2d2ff94dd0138c3ecfb91db634464a9afb4c8e6b50f0a67e00 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.0.tar.gz (85 kB)\n",
      "\u001b[K     |████████████████████████████████| 85 kB 18.1 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4e8fb227a7914a9f9667cedcf34034d2/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4e8fb227a7914a9f9667cedcf34034d2/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-angn571g\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4e8fb227a7914a9f9667cedcf34034d2/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4e8fb227a7914a9f9667cedcf34034d2/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4e8fb227a7914a9f9667cedcf34034d2/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4e8fb227a7914a9f9667cedcf34034d2/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/05/73/fac741eef89b0257fb1807de80e96474f40d52739cdbc32c90c4a793e79d/mysqlclient-1.4.0.tar.gz#sha256=efeaacd04feea7d44fef2a5adf4df335b438458f8b89144307dc5a90025761a5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.14.tar.gz (91 kB)\n",
      "\u001b[K     |████████████████████████████████| 91 kB 27.7 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_016ebf3ccc0746c7b003e4702a2a105c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_016ebf3ccc0746c7b003e4702a2a105c/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-79kcxjdg\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_016ebf3ccc0746c7b003e4702a2a105c/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_016ebf3ccc0746c7b003e4702a2a105c/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_016ebf3ccc0746c7b003e4702a2a105c/setup_posix.py\", line 53, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_016ebf3ccc0746c7b003e4702a2a105c/setup_posix.py\", line 28, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f7/a2/1230ebbb4b91f42ad6b646e59eb8855559817ad5505d81c1ca2b5a216040/mysqlclient-1.3.14.tar.gz#sha256=3981ae9ce545901a36a8b7aed76ed02960a429f75dc53b7ad77fb2f9ab7cd56b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.13.tar.gz (90 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[K     |████████████████████████████████| 90 kB 8.2 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_e443847bed214bf485444d7286887399/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_e443847bed214bf485444d7286887399/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-e9erx9ve\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_e443847bed214bf485444d7286887399/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_e443847bed214bf485444d7286887399/setup.py\", line 18, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_e443847bed214bf485444d7286887399/setup_posix.py\", line 53, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_e443847bed214bf485444d7286887399/setup_posix.py\", line 28, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz#sha256=ff8ee1be84215e6c30a746b728c41eb0701a46ca76e343af445b35ce6250644f (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.12.tar.gz (89 kB)\n",
      "\u001b[K     |████████████████████████████████| 89 kB 19.9 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5216b9a64a394c62ad8b5d8b1826271d/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5216b9a64a394c62ad8b5d8b1826271d/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-f2yj5_h9\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5216b9a64a394c62ad8b5d8b1826271d/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5216b9a64a394c62ad8b5d8b1826271d/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5216b9a64a394c62ad8b5d8b1826271d/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5216b9a64a394c62ad8b5d8b1826271d/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz#sha256=2d9ec33de39f4d9c64ad7322ede0521d85829ce36a76f9dd3d6ab76a9c8648e5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.11.tar.gz (89 kB)\n",
      "\u001b[K     |████████████████████████████████| 89 kB 17.3 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_ce1caab6ff1947049a5541f9f7c9f6ea/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_ce1caab6ff1947049a5541f9f7c9f6ea/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-il_o8wju\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_ce1caab6ff1947049a5541f9f7c9f6ea/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_ce1caab6ff1947049a5541f9f7c9f6ea/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_ce1caab6ff1947049a5541f9f7c9f6ea/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_ce1caab6ff1947049a5541f9f7c9f6ea/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6a/4d/856d1848e9b7fa8577a31c0188592f472e5cbc94f588c2a40ff930533d73/mysqlclient-1.3.11.tar.gz#sha256=9a79b38843d61f651266ff16b9fdcc8830d21f0fb852e4406a19e9a715bdf3e2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.10.tar.gz (82 kB)\n",
      "\u001b[K     |████████████████████████████████| 82 kB 1.3 MB/s  eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_332664c3b7524efea73388c628bf9e88/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_332664c3b7524efea73388c628bf9e88/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-ep14bkt1\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_332664c3b7524efea73388c628bf9e88/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_332664c3b7524efea73388c628bf9e88/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_332664c3b7524efea73388c628bf9e88/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_332664c3b7524efea73388c628bf9e88/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/40/9b/0bc869f290b8f49a99b8d97927f57126a5d1befcf8bac92c60dc855f2523/mysqlclient-1.3.10.tar.gz#sha256=452aaf9d2ba1a4fb85c134c88f9b1857852deed63b3b13255d7a65d2c1297262 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.9.tar.gz (81 kB)\n",
      "\u001b[K     |████████████████████████████████| 81 kB 23.3 MB/s eta 0:00:01\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4d1e03d674524865b426e6f0cd613a80/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4d1e03d674524865b426e6f0cd613a80/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-ci1_nolz\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4d1e03d674524865b426e6f0cd613a80/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4d1e03d674524865b426e6f0cd613a80/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4d1e03d674524865b426e6f0cd613a80/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_4d1e03d674524865b426e6f0cd613a80/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/db/f5/c8e1657985c31dda16e434edf5257c31572fa5faacd7e48b1618390e4b18/mysqlclient-1.3.9.tar.gz#sha256=990ccf1e1f15b9a291b811c993dc1c216566714bc14e6581b38665bd61c28c99 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.8.tar.gz (81 kB)\n",
      "\u001b[K     |████████████████████████████████| 81 kB 19.2 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_2d3d5414a2834c0580bf5f3bbcb329a4/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_2d3d5414a2834c0580bf5f3bbcb329a4/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-_ya7u6ji\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_2d3d5414a2834c0580bf5f3bbcb329a4/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_2d3d5414a2834c0580bf5f3bbcb329a4/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_2d3d5414a2834c0580bf5f3bbcb329a4/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_2d3d5414a2834c0580bf5f3bbcb329a4/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/31/ce/7ea049b3d5929b3cce3104967ccca218a9f054517f0d15dfdaf4e76da2a0/mysqlclient-1.3.8.tar.gz#sha256=c64bc386c0b771ed6ff76de0f52e0f957f98d9e13c83b0ddb821afdbe3f5d970 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.7.tar.gz (79 kB)\n",
      "\u001b[K     |████████████████████████████████| 79 kB 11.8 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5611cf5e158847989d07d22e94c67974/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5611cf5e158847989d07d22e94c67974/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-934kd_m9\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5611cf5e158847989d07d22e94c67974/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5611cf5e158847989d07d22e94c67974/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5611cf5e158847989d07d22e94c67974/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_5611cf5e158847989d07d22e94c67974/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/74/ff/4e964e20b559e55d7afa60fbccc6a560f2adf289813bd3d7eb4eb8a87093/mysqlclient-1.3.7.tar.gz#sha256=c74a83b4cb2933d0e43370117eeebdfa03077ae72686d2df43d31879267f1f1b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.6.tar.gz (78 kB)\n",
      "\u001b[K     |████████████████████████████████| 78 kB 21.8 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_885dd4b2ab3342b8a9efec839f7ae1a9/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_885dd4b2ab3342b8a9efec839f7ae1a9/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-zh5u6jo_\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_885dd4b2ab3342b8a9efec839f7ae1a9/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_885dd4b2ab3342b8a9efec839f7ae1a9/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_885dd4b2ab3342b8a9efec839f7ae1a9/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_885dd4b2ab3342b8a9efec839f7ae1a9/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/09/29/6648563af4b45798ba667f17ea55166d7b0ed8717937c06977a1fdbe7df6/mysqlclient-1.3.6.tar.gz#sha256=1f63a8ab111530a0ff9acaeb118074f11e7564b7c124f2e7fc56fcac641aecf2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.5.tar.gz (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 9.1 MB/s eta 0:00:01\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_87869de456e84e70837d899fe110a8b3/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_87869de456e84e70837d899fe110a8b3/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-l_ekourf\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_87869de456e84e70837d899fe110a8b3/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_87869de456e84e70837d899fe110a8b3/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_87869de456e84e70837d899fe110a8b3/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_87869de456e84e70837d899fe110a8b3/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/82/ea/336daf6c7baa564d0c434ab748218d1a7dc61dfc7066e98b72afd24fd2b9/mysqlclient-1.3.5.tar.gz#sha256=80ea68f6f3c2cfbf35c91adde2b40de1f2c31132118d2dcee048c72423f678bf (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.4.tar.gz (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 14.7 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_11f77920e36542a2821b32ccfd7f9e46/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_11f77920e36542a2821b32ccfd7f9e46/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-to_a6bhi\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_11f77920e36542a2821b32ccfd7f9e46/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_11f77920e36542a2821b32ccfd7f9e46/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_11f77920e36542a2821b32ccfd7f9e46/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_11f77920e36542a2821b32ccfd7f9e46/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/17/d9/03b08e6a033401335b720806b87596aee8d7f7aa87539713238905c4a8d1/mysqlclient-1.3.4.tar.gz#sha256=a0263383f8ac33ad12d68dc61fa8ccbee41244ce916287c6cee71bf8aea82c5c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.3.tar.gz (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 22.9 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0488dc23a82e4d1596ea759539c79ffd/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0488dc23a82e4d1596ea759539c79ffd/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-a1y3p1za\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0488dc23a82e4d1596ea759539c79ffd/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0488dc23a82e4d1596ea759539c79ffd/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0488dc23a82e4d1596ea759539c79ffd/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0488dc23a82e4d1596ea759539c79ffd/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/26/53/c575db342bfca0213c9243ed2642bfadcd420b18d2f477dc812543e3d83a/mysqlclient-1.3.3.tar.gz#sha256=0f0887882d71bf2a079d9724d9323053cfbee8ab2dcfc989daf97d7ce5be9af9 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.2.tar.gz (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 23.5 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8044eeaeda8043c280bd31811c9bfb09/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8044eeaeda8043c280bd31811c9bfb09/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-gdm50ytp\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8044eeaeda8043c280bd31811c9bfb09/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8044eeaeda8043c280bd31811c9bfb09/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8044eeaeda8043c280bd31811c9bfb09/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_8044eeaeda8043c280bd31811c9bfb09/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2d/df/5440ee86bbb248325cdd6e1fc9cbbba365018a0d2d57f673610e020e6b1d/mysqlclient-1.3.2.tar.gz#sha256=e44025830501b9f70f8c2fe8eeff66f0df2df198802f7295801dac199b8236ef (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.1.tar.gz (76 kB)\n",
      "\u001b[K     |████████████████████████████████| 76 kB 19.7 MB/s eta 0:00:01\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_f2671d09bb8d4739b0e866b160360ab3/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_f2671d09bb8d4739b0e866b160360ab3/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-gwckexfe\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_f2671d09bb8d4739b0e866b160360ab3/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_f2671d09bb8d4739b0e866b160360ab3/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_f2671d09bb8d4739b0e866b160360ab3/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_f2671d09bb8d4739b0e866b160360ab3/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6b/ba/4729d99e85a0a35bb46d55500570de05b4af10431cef174b6da9f58a0e50/mysqlclient-1.3.1.tar.gz#sha256=3549e8a61f10c8cd8eac6581d3f44d0594f535fb7b29e6090db3a0bc547b25ad (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.0.tar.gz (76 kB)\n",
      "\u001b[K     |████████████████████████████████| 76 kB 19.2 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0884630c141b4b7db86dad92dfe7d15c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0884630c141b4b7db86dad92dfe7d15c/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-pxwq3b23\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0884630c141b4b7db86dad92dfe7d15c/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0884630c141b4b7db86dad92dfe7d15c/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0884630c141b4b7db86dad92dfe7d15c/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysqlclient_0884630c141b4b7db86dad92dfe7d15c/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25hCollecting mysql\n",
      "  Downloading mysql-0.0.2.tar.gz (1.9 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_243f63d98d9d4234bf6ccf2b61fe885f/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_243f63d98d9d4234bf6ccf2b61fe885f/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-zp637uw8\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_243f63d98d9d4234bf6ccf2b61fe885f/\n",
      "    Complete output (32 lines):\n",
      "    WARNING: `mysql` is a virtual package. Please use `%s` as a dependency directly.\n",
      "    \n",
      "    running egg_info\n",
      "    creating /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-zp637uw8/mysql.egg-info\n",
      "    writing /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-zp637uw8/mysql.egg-info/PKG-INFO\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_243f63d98d9d4234bf6ccf2b61fe885f/setup.py\", line 33, in <module>\n",
      "        setup(\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 87, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py\", line 148, in setup\n",
      "        return run_commands(dist)\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py\", line 163, in run_commands\n",
      "        dist.run_commands()\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 967, in run_commands\n",
      "        self.run_command(cmd)\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 1214, in run_command\n",
      "        super().run_command(command)\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 291, in run\n",
      "        writer(self, ep.name, os.path.join(self.egg_info, ep.name))\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 655, in write_pkg_info\n",
      "        metadata.write_pkg_info(cmd.egg_info)\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 1118, in write_pkg_info\n",
      "        self.write_pkg_file(pkg_info)\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 193, in write_pkg_file\n",
      "        license = rfc822_escape(self.get_license())\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/util.py\", line 494, in rfc822_escape\n",
      "        lines = header.split('\\n')\n",
      "    AttributeError: 'list' object has no attribute 'split'\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/bf/5f/b574ac9f70811df0540e403309f349a8b9fa1a25d3653824c32e52cc1f28/mysql-0.0.2.tar.gz#sha256=55e66b5e7b3823b1da5fb2a063e95a628fb850b2a0b76bdcd884faac5d2daa7d (from https://pypi.org/simple/mysql/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading mysql-0.0.1.tar.gz (1.7 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\r\n",
      "     command: /Users/MilesChild/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_27dff9f9a51d4c58bed133a5147c5044/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_27dff9f9a51d4c58bed133a5147c5044/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-ub0kg6u7\r\n",
      "         cwd: /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_27dff9f9a51d4c58bed133a5147c5044/\r\n",
      "    Complete output (30 lines):\r\n",
      "    running egg_info\r\n",
      "    creating /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-ub0kg6u7/mysql.egg-info\r\n",
      "    writing /private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-pip-egg-info-ub0kg6u7/mysql.egg-info/PKG-INFO\r\n",
      "    Traceback (most recent call last):\r\n",
      "      File \"<string>\", line 1, in <module>\r\n",
      "      File \"/private/var/folders/rs/k8yvpht95zxbr8d7v79msjk00000gn/T/pip-install-t_zlq4j8/mysql_27dff9f9a51d4c58bed133a5147c5044/setup.py\", line 28, in <module>\r\n",
      "        setup(\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 87, in setup\r\n",
      "        return distutils.core.setup(**attrs)\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py\", line 148, in setup\r\n",
      "        return run_commands(dist)\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py\", line 163, in run_commands\r\n",
      "        dist.run_commands()\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 967, in run_commands\r\n",
      "        self.run_command(cmd)\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 1214, in run_command\r\n",
      "        super().run_command(command)\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\r\n",
      "        cmd_obj.run()\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 291, in run\r\n",
      "        writer(self, ep.name, os.path.join(self.egg_info, ep.name))\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 655, in write_pkg_info\r\n",
      "        metadata.write_pkg_info(cmd.egg_info)\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 1118, in write_pkg_info\r\n",
      "        self.write_pkg_file(pkg_info)\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 193, in write_pkg_file\r\n",
      "        license = rfc822_escape(self.get_license())\r\n",
      "      File \"/Users/MilesChild/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/util.py\", line 494, in rfc822_escape\r\n",
      "        lines = header.split('\\n')\r\n",
      "    AttributeError: 'list' object has no attribute 'split'\r\n",
      "    ----------------------------------------\u001b[0m\r\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/06/ef/c4efbf2a51fb46aba9be03a973638d9539c9ca10a5259b2cbb1a66133b2e/mysql-0.0.1.tar.gz#sha256=ca87a58c42b6588bafc76f3f5402073b595fc0f5cf1d027af38662bb9932f49f (from https://pypi.org/simple/mysql/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\r\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement mysqlclient (from mysql) (from versions: 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11rc1, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.4.0rc1, 1.4.0rc2, 1.4.0rc3, 1.4.0, 1.4.1, 1.4.2, 1.4.2.post1, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0rc1, 2.1.0, 2.1.1)\u001b[0m\r\n",
      "\u001b[31mERROR: No matching distribution found for mysqlclient\u001b[0m\r\n"
     ]
    },
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'mysql'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[0;32mIn [9]\u001b[0m, in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m get_ipython()\u001b[38;5;241m.\u001b[39msystem(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mpip install mysql\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmysql\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mconnector\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01msys\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mboto3\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'mysql'"
     ]
    }
   ],
   "source": [
    "import mysql.connector\n",
    "import sys\n",
    "import boto3\n",
    "import os\n",
    "\n",
    "ENDPOINT=\"dev-lightning-db.cygxsxxfo1d6.us-east-1.rds.amazonaws.com\"\n",
    "PORT=\"3306\"\n",
    "USER=\"admin\"\n",
    "REGION=\"us-east-1\"\n",
    "DBNAME=\"\"\n",
    "os.environ['LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN'] = '1'\n",
    "\n",
    "#gets the credentials from .aws/credentials\n",
    "#session = boto3.Session(profile_name='default')\n",
    "#client = session.client('rds')\n",
    "\n",
    "#token = client.generate_db_auth_token(DBHostname=ENDPOINT, Port=PORT, DBUsername=USER, Region=REGION)\n",
    "\n",
    "try:\n",
    "    conn =  mysql.connector.connect(host=ENDPOINT, user=USER, passwd='ntslightningtest', port=PORT, database=DBNAME, ssl_ca='SSLCERTIFICATE')\n",
    "    cur = conn.cursor()\n",
    "    cur.execute(\"\"\"SELECT now()\"\"\")\n",
    "    query_results = cur.fetchall()\n",
    "    print(query_results)\n",
    "except Exception as e:\n",
    "    print(\"Database connection failed due to {}\".format(e))   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d2a57f92",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.9 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.9"
  },
  "vscode": {
   "interpreter": {
    "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
